### ISSUE TITLE
Question: How to pass the parms?

### ISSUE THREAD

**Issue by LogeswaranA** [jiandaoyun/sso-saml-node#1]
Hi There -
Your repo looks interesting & simple to understand, but after I execute " node app.js " , how do I test it ?

in my browser , from localhost:8080/sso it shows "ERR_REDIRECT_FLOW_BAD_ARGS" . please suggest.

thanks
Lokesh

**Comment by AngelMsger** [comment]
Thanks for your try!

The **main goal** of this demo is to serve the users of [jiandaoyun](https://www.jiandaoyun.com/). Take the website's SSO flow for example, the endpoint of this demo(localhost:8080/sso) **cannot** be visited directly without SAML params. A SAML request should be initiated by the website(SP) with corresponding "REDIRECT_FLOW_ARGS". Then this demo will handle these params and then return the results according to SAML protocol.

The endpoint needs two query params:
* SAMLRequest: SAML request(XML content) encoded by Base64
* RelayState: a random state code to avoid csrf.

**e.g.** -- http://localhost:8080/sso?SAMLRequest=pZJLT8MwEIT%2FSuR7EjuPplhtpdIKUalA1RYOXJCbrFtLjl28Do9%2Fj5uCBAe4cF3vzOib9QhFq4982vmDWcNzB%2Bijt1Yb5P3DmHTOcCtQITeiBeS%2B5pvpzZJnCeVHZ72trSbfJH8rBCI4r6wh0WI%2BJk%2BMMppnMo%2BlzAdxwSTEw0JWcVnkDKqqyMqCkegBHAbNmASLIETsYGHQC%2BPDiLKLmA7jrNrSjNOcl2UyyNkjieaBRRnhe%2BXB%2ByNPU21roQ8WPR%2FSIU0RLYlWnxSXyjTK7P8G2J2XkF9vt6t4dbfZkmj6BTWzBrsW3Abci6rhfr08B2NIbuAlEWYPusU9uKS27Sk9PVWWlk0GTTNgsqpyeVHloZTdri5ZKmokk9Fph%2FfUbvIvO4U4Sr%2B7jc7Xvw2Yi%2FnKalW%2FR1fWtcL%2F3gJLWD9RTSz7VQ6tUHraNA4QQxta29eZA%2BFhTKTQCCSdnGN%2F%2FrPJBw%3D%3D&RelayState=a6f4016545e616cd0d0b962

Although this demo is implemented just for SSO flow with _jiandaoyun_, you can use it for whatever you want. However, if you don't use _jiandaoyun_ and just look for a SAML solution for Node.js, maybe [samlify](https://github.com/tngan/samlify) is better.

Feel free to reopen the issue or contact me if the question not solved.
